# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

pr:
- master
- releases/*

trigger:
- master

jobs:

- job: 'Adequacy'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - bash: make clean install
    displayName: 'Adequacy Tests'

- job: 'LinuxInstall'
  dependsOn: Adequacy
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python setup.py install
      dynaconf init -v FOO=running_on_travis -y
      dynaconf write toml -v OTHERVALUE=Hello_Travis -y
      dynaconf list | grep -c running_on_travis
      dynaconf list | grep -c Hello_Travis
      dynaconf --version
    displayName: 'Install and test cli'

- job: 'LinuxUnit'
  dependsOn: Adequacy
  variables:
    - group: codecov
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: source .ci/install_dev.sh
    displayName: 'Install dependencies'

  - script: source .ci/test.sh
    displayName: 'tests'

  - script: codecov --token $(SECRET_CODECOV_TOKEN)
    displayName: 'Publish Coverage'
    condition: eq(variables['python.version'], '3.7')

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'LinuxUnit Python $(python.version)'
    condition: succeededOrFailed()

- job: 'LinuxFunctional'
  dependsOn: Adequacy
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: source .ci/install_dev.sh
    displayName: 'Install dependencies'

  - bash: make test_examples
    displayName: 'Functional tests for examples and frameworks'

- job: 'MacOSInstall'
  dependsOn: Adequacy
  pool:
    vmImage: 'macOS-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python setup.py install
      dynaconf init -v FOO=running_on_travis -y
      dynaconf write toml -v OTHERVALUE=Hello_Travis -y
      dynaconf list | grep -c running_on_travis
      dynaconf list | grep -c Hello_Travis
      dynaconf --version
    displayName: 'Install and test cli'

- job: 'MacOSUnit'
  dependsOn: Adequacy
  variables:
    - group: codecov
  pool:
    vmImage: 'macOS-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: source .ci/install_dev.sh
    displayName: 'Install dependencies'

  - script: py.test -v --cov-config .coveragerc --cov=dynaconf -l tests/ --junitxml=junit/test-results.xml -m "not integration"
    displayName: 'tests'

  - script: codecov --token $(SECRET_CODECOV_TOKEN)
    displayName: 'Publish Coverage'
    condition: eq(variables['python.version'], '3.7')

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'MacOSUnit Python $(python.version)'
    condition: succeededOrFailed()

- job: 'macOSFunctional'
  dependsOn: Adequacy
  pool:
    vmImage: 'macOS-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: source .ci/install_dev.sh
    displayName: 'Install dependencies'

  - bash: make test_examples
    displayName: 'Functional tests for examples and frameworks'

- job: 'Redis'
  dependsOn: Adequacy
  variables:
    REDIS_ENABLED_FOR_DYNACONF: true
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      docker pull redis:alpine
      # Let tests run the container
      # docker run -d -p 6379:6379 redis
      docker ps -a
    displayName:  'Run Redis Container'

  - script: source .ci/install_dev.sh
    displayName: 'Install dependencies'

  - bash: make test_redis
    displayName: 'Functional test for redis'

- job: 'Vault'
  dependsOn: Adequacy
  variables:
    VAULT_ENABLED_FOR_DYNACONF: true
    VAULT_TOKEN_FOR_DYNACONF: myroot
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      docker pull vault
      # Let tests run the container
      # docker run -d -e 'VAULT_DEV_ROOT_TOKEN_ID=myroot' -p 8200:8200 vault
      docker ps -a
    displayName:  'Run Vault Container'

  - script: source .ci/install_dev.sh
    displayName: 'Install dependencies'

  - bash: make test_vault
    displayName: 'Functional test for vault'

- job: 'WindowsUnit'
  dependsOn: Adequacy
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      python37:
        python.version: '3.7'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      python -m pip install -r requirements_dev.txt
      py.test -v -l tests --junitxml=junit/test-results.xml -m "not integration"
    displayName: Test

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'WindowsUnit Python $(python.version)'
    condition: succeededOrFailed()

- job: 'WindowsInstall'
  dependsOn: Adequacy
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      python37:
        python.version: '3.7'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python setup.py install
      dynaconf init -v FOO=running_on_travis -y
      dynaconf write toml -v OTHERVALUE=Hello_Travis -y
      dynaconf list | grep -c running_on_travis
      dynaconf list | grep -c Hello_Travis
      dynaconf --version
    displayName: 'Install and test cli'

- job: 'WindowsFunctional'
  dependsOn: Adequacy
  variables:
      DJANGO_SETTINGS_MODULE: foo.settings
      PYTHONPATH: '.'
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      python37:
        python.version: '3.7'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install -r requirements_dev.txt
      python setup.py install
      setlocal enableextensions enabledelayedexpansion
      @echo on
      pushd example\common & cd & python program.py & popd
      pushd example\common-encoding & cd & python program.py & popd
      pushd example\ & cd & python full_example.py & popd
      pushd example\ & cd & python compat.py & popd
      pushd example\app & cd & python app.py  & popd
      pushd example\app_with_dotenv & cd & python app.py & popd
      pushd example\merge_enabled & cd & python app.py & popd
      pushd example\new_merge & cd & python app.py & popd
      pushd example\dynaconf_merge & cd & python app.py & popd
      pushd example\multiple_sources & cd & python app.py & popd
      pushd example\multiple_folders & cd & python app.py & popd
      pushd example\toml_example\ & cd & python app.py & popd
      pushd example\yaml_example\settings_file\ & cd & python app.py & popd
      pushd example\yaml_example\yaml_as_extra_config\ & cd & python app.py & popd
      pushd example\flask_with_dotenv & cd & flask routes & popd
      pushd example\flask_with_toml & cd & flask routes & popd
      pushd example\flask_with_yaml & cd & flask routes & popd
      pushd example\flask_with_json & cd & flask routes & popd
      pushd example\flask_with_commentjson & cd & flask routes & popd
      pushd example\flask_with_ini & cd & flask routes & popd
      pushd example\validators\with_python\ & cd & python app.py & popd
      pushd example\validators\with_toml\ & cd & dynaconf validate & popd
      pushd example\toml_with_secrets\ & cd & python program.py & popd
      pushd example\envs & cd & python app.py & popd
      pushd example\custom_loader & cd & python app.py & popd
      pushd example\get_fresh & cd & python app.py & popd
      pushd example\includes & cd & python app.py & popd
      pushd example\jenkins_secrets_file & cd & python app.py & popd
      pushd example\specific_settings_files & cd & python app.py & popd
      pushd example\django_example\ & cd & python manage.py test polls -v 2 & popd
      pushd example\django_example\ & cd & django-admin test polls -v 2 & popd

    displayName: 'Run functional examples'
