default:
  host: server.com
  port: 5000
development:
  environment: this is development
  host: dev_server.com
  works: yaml_as_extra_config
production:
  environment: this is production
  host: prod_server.com
