[development]
database = {passwd='1234', dynaconf_merge=true}
plugins = ['secret', 'dynaconf_merge']
scripts = ['encrypt.sh', 'dynaconf_merge_unique']

[production]
database = {passwd='666', dynaconf_merge=true}
