site_name: Dynaconf - 3.1.11
site_url: https://dynaconf.com
site_description: Configuration Management for Python
site_author: Bruno Rocha
repo_name: dynaconf/dynaconf
repo_url: https://github.com/dynaconf/dynaconf
edit_uri: https://github.com/dynaconf/dynaconf/tree/master/docs
nav:
- Home: index.md
- Languages:
  - en: /
  - es: /es/
  - fr: /fr/
  - pt_BR: /pt_BR/
- Env vars: envvars.md
- Settings files: settings_files.md
- Secrets: secrets.md
- Merging: merging.md
- Dynamic Variables: dynamic.md
- CLI: cli.md
- Validation: validation.md
- Flask: flask.md
- Django: django.md
- Advanced usage: advanced.md
theme:
  features:
  - search.suggest
  - search.highlight
  - search.share
  - content.code.annotate
  name: material
  language: en
  logo: img/logo_square_d.svg
  favicon: img/favicon.ico
  palette:
  - scheme: default
    media: '(prefers-color-scheme: light)'
    primary: white
    accent: teal
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  - scheme: slate
    media: '(prefers-color-scheme: dark)'
    primary: black
    accent: teal
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
markdown_extensions:
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji ''
    emoji_generator: !!python/name:materialx.emoji.to_svg ''
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tilde
- admonition
- codehilite:
    guess_lang: false
- toc:
    permalink: true
plugins:
- git-revision-date
- search:
    lang: en
    prebuild_index: true
extra:
  disqus: dynaconf
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/dynaconf/dynaconf
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/rochacbruno
  - icon: fontawesome/brands/linkedin
    link: https://linkedin.com/in/rochacbruno
  - icon: fontawesome/brands/twitch
    link: https://twitch.tv/codeshow
  alternate:
  - link: /
    name: en - English
  - link: /pt_BR/
    name: pt_BR - Portuguese (Brazil)
