[default]
port = 5555
[development]
server = 'devserver.com'
[production]
server = 'prodserver.com'
[staging]
server = 'stagserver.com'
[testing]
server = 'testserver.com'
[mycustomenv]
server = 'customserver.com'
[global]
username = 'admin'
