[lint]
select =[
    "T100", # Covers flake-debugger
    # https://docs.astral.sh/ruff/rules/#flake8-todos-td
    "TD001", # Covers flake8-todos
    "TD004", # Covers flake8-todos
    "TD005", # Covers flake8-todos
    "TD006", # Covers flake8-todos
    "TD007", # Covers flake8-todos
]
