nt = [
    "app_with_dotenv",
    "configure",
    "custom_cast_token",
    "envless_mode",
    "format",
    "django_example",
    "django_example_compat",
    "django_pytest",
    "djang_pytest_pure",
    "flask_with_commentjson",
    "project_root",
    "settings_file",
    "toml_with_secrets",
    "160_path_traversal_fixed",
    "184_ipython",
    "434_setenv",
    "449_django_lazy_path",
    "685_disable_dotted_lookup",
    "741_envvars_ignored",
    "missing_pwd",
    "876_deleted_cwd",
    "982_wildcard",
    "1037_django_explicit_mode",
]
