name: 'Install from artifact'
description: 'Setup Python and install Dynaconf wheel from artifact with optional dependencies'

inputs:
  artifact_in:
    description: 'Name of the artifact containing the distribution'
    required: true
  dependencies:
    description: 'Optional dependencies to install with the wheel'
    required: false
    default: ''
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.10'

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v8.2.0
      with:
        enable-cache: true

    - name: Download wheel
      uses: actions/download-artifact@v8
      with:
        name: ${{ inputs.artifact_in }}
        path: dist/

    - name: Install from wheel
      shell: bash
      run: |
        make install \
          WHEEL=dist/*.whl \
          GROUP=${{ inputs.dependencies }} \
          PYTHON=${{ inputs.python-version }}
