name: Build and Deploy to Netlify

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      checkout_refspec:
        description: "If provided, its passed to `git checkout <checkout_refspec>` before building."

# https://github.com/marketplace/actions/netlify-actions#usage
jobs:
  build-docs:
    uses: ./.github/workflows/main/docs-build.yml
    with:
      dynaconf_ref: ${{ github.event.inputs.checkout_refspec }}

  deploy:
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
      - name: Download documentation
        uses: actions/download-artifact@v4
        with:
          name: docs-site
          path: site

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './site'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
