# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [master]
    paths-ignore: # run if anything different from these is modified
      - "docs/**"
      - "mkdocs.yml"

  pull_request:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "mkdocs.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# When a Push is made on an existing branch/PR
# it cancels any pre running job and
# let only the latest executing
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  docs:
    uses: ./.github/workflows/main/docs-build.yml

  lint:
    uses: ./.github/workflows/main/lint.yml

  build:
    needs: lint
    uses: ./.github/workflows/main/build.yml
    with:
      python_version: "3.9"
      artifact_out: "dynaconf_dist"

  tests:
    needs: build
    uses: ./.github/workflows/main/test.yml
    with:
      artifact_in: "dynaconf_dist"
      python_minimal: '["3.9", "3.13"]'
      python_full: '["3.9", "3.10", "3.11", "3.12", "3.13"]'
      python_latest: '3.13'
    secrets: inherit

  benchmark:
    needs: build
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/main/benchmark.yml

  checkpoint:
    runs-on: ubuntu-latest
    needs:
      - lint
      - build
      - docs
      - tests
    steps:
      - name: All tests has passed
        run: echo "All tests has passed"
