name: Create Release Commit

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release tag (e.g. 3.2.1)"
      release-again:
        description: "Just checking."

jobs:
  release-commit:
    name: "Create release commit"
    if: ${{ inputs.release == inputs.release-again }}
    uses: ./.github/workflows/release/release-commit.yml
    with:
      release: ${{ inputs.release }}
    secrets: inherit

  publish-all:
    name: "Publish all"
    needs: release-commit
    uses: ./.github/workflows/release/publish-all.yml
    with:
      release: ${{ inputs.release }}
    secrets: inherit
