name: Create Release Commit

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: "Release tag (e.g. 3.2.1)"
        required: true
        type: string

jobs:
  # Validate release readiness
  # This outputs individual validation for version-bump, pypi, github and docs.
  validate-release:
    name: "Validate release"
    uses: ./.github/workflows/release__validate-release.yml
    with:
      release-tag: ${{ inputs.release-tag }}
    secrets: inherit

  # Create version bump commits
  # Skip if a version-bump commit already exist for this release-tag
  # E.g: it may have been done manually but we want to release with CI
  version-bump:
    name: "Create release commits"
    needs: validate-release
    if: ${{ needs.validate-release.outputs.version-bump-ok == 'true' }}
    uses: ./.github/workflows/release__version-bump.yml
    with:
      release-tag: ${{ inputs.release-tag }}
    secrets: inherit

  # Generate release artifacts
  build-dist:
    name: "Build distribution"
    needs:
      - version-bump
      - validate-release
    uses: ./.github/workflows/main__build-dist.yml
    with:
      release-tag: ${{ inputs.release-tag }}

  build-docs:
    name: "Build documentation"
    needs:
      - version-bump
      - validate-release
    uses: ./.github/workflows/main__build-docs.yml
    with:
      release-tag: ${{ inputs.release-tag }}

  # Push to prod
  publish-all:
    name: "Publish all"
    needs:
      - validate-release
      - build-dist
      - build-docs
    uses: ./.github/workflows/release__publish-all.yml
    with:
      release-tag: ${{ inputs.release-tag }}
      dist-artifact: ${{ needs.build-dist.outputs.dist-artifact }}
      docs-artifact: ${{ needs.build-docs.outputs.docs-artifact }}
      release-notes-artifact: ${{ needs.build-docs.outputs.release-notes-artifact }}
      # Publishing is idempotent. E.g., if only pypi-ok is 'false', only the pypi
      # publish will be triggered.
      pypi-ok: ${{ needs.validate-release.outputs.pypi-ok }}
      github-ok: ${{ needs.validate-release.outputs.github-ok }}
      docs-ok: ${{ needs.validate-release.outputs.docs-ok }}
    secrets: inherit
