name: Update CONTRIBUTORS file
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: minicli/action-contributors@v3.3
        name: "Update a projects CONTRIBUTORS file"
        env:
          CONTRIB_REPOSITORY: 'dynaconf/dynaconf'
          CONTRIB_OUTPUT_FILE: 'CONTRIBUTORS.md'
      - name: Create a PR
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update Contributors
          title: "[automated] Update Contributors File"
          token: ${{ secrets.GITHUB_TOKEN }}

#       - name: Update resources
#         uses: test-room-7/action-update-file@v1
#         with:
#           file-path: 'CONTRIBUTORS.md'
#           commit-msg: Update Contributors
#           github-token: ${{ secrets.GITHUB_TOKEN }}
